
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool: 'windows'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: InstallFortifySCA@7
  inputs:
    InstallerPath: 'C:\Program Files\Fortify\Fortify_SCA_and_Apps_20.2.0\'
    VS2015: false
    VS2019: true
    LicenseFile: 'C:\Program Files\Fortify\Fortify_SCA_and_Apps_20.2.0\fortify.license'
    RunFortifyRulepackUpdate: false